version: "3.9"

services:
  dev:
    container_name: anmol-node-dev
    image: paritytech/ci-linux:ba887019-20210411

    ports:
      - 9944:9944
      - 3000:3000

    volumes:
      - .:/builds:delegated
      - binaries:/builds/target

    command: bash -c "cargo build --release && ./target/release/anmol --dev --ws-external"

volumes:
  binaries:
