version: "3.9"

services:
  dev:
    image: anmolnetwork/anmol:development
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - dev-extensions:/home/anmol/.vscode-server/extensions

    user: anmol:anmol

    # Enables a ptrace-based debugger like C++, Go, and Rust.
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  dev-extensions:
