name: Build Anmol

on:
  push:
    branches: [ master, ibtida ]
  workflow_dispatch:

jobs:
  build-anmol:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set testnet env
        if: endsWith(github.ref, '/ibtida')
        run: |
          echo "ENVIRONMENT=testnet" >> $GITHUB_ENV

      - name: Set production env
        if: endsWith(github.ref, '/master')
        run: |
          echo "ENVIRONMENT=production" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: |
            /tmp/.buildx-cache-base
            /tmp/.buildx-cache-prod
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push base image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.build
          push: true
          tags: anmolnetwork/anmol-node-build:latest-${{ env.TAG}}
          cache-from: type=local,src=/tmp/.buildx-cache-base
          cache-to: type=local,dest=/tmp/.buildx-cache-base-new
          build-args: |
            TAG=${{ env.ENVIRONMENT }}

      - name: Build and push prod image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: anmolnetwork/anmol-node:latest-${{ env.TAG }}
          cache-from: type=local,src=/tmp/.buildx-cache-prod
          cache-to: type=local,dest=/tmp/.buildx-cache--prod-new
          build-args: |
            TAG=${{ env.ENVIRONMENT }}

        # TODO: step to deploy to AWS

        # This ugly bit is necessary if you don't want your cache to grow forever
        # till it hits GitHub's limit of 5GB.
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache-base
          rm -rf /tmp/.buildx-cache-prod
          mv /tmp/.buildx-cache-base-new /tmp/.buildx-cache-base
          mv /tmp/.buildx-cache--prod-new /tmp/.buildx-cache-prod
