# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build Node

on:
  push:
    branches:
      - 'master'
      - 'ibtida'

    tags:
      - 'v*'

  pull_request:
    branches:
      - 'master'
      - 'ibtida'

jobs:
  build-docker-images:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v1.0.0
        with:
          files: Dockerfile.build

      - name: Build and push builder image
        uses: docker/build-push-action@v2
        if: ${{ steps.changed-files-specific.outputs.any_changed == 'true' }}
        with:
          file: ./Dockerfile.build
          push: ${{ github.event_name != 'pull_request' }}
          tags: anmolnetwork/anmol-node-build:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: anmolnetwork/anmol-node
          tags: |
            type=ref,event=branch
            type=ref,event=tag

      - name: Build and push production image
        uses: docker/build-push-action@v2
        with:
          build-args: |
            BUILD_DATE=${{ steps.date.outputs.date }}
            GIT_SHORT_SHA=${{ github.sha }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
