# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Check & Benchmarking

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events
  push:
    branches:
      - 'master'
      - 'ibtida'

  pull_request:
    branches:
      - 'master'
      - 'ibtida'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

  lint:
    needs: checkout

    runs-on: ubuntu-20.04
    container:
      image: anmolnetwork/anmol-node-build:latest

    steps:
      - name: Lint Code
        run: |
          cargo fmt -- --check

  test-and-benchmark:
    needs: checkout

    runs-on: ubuntu-20.04
    container:
      image: anmolnetwork/anmol-node-build:latest

    steps:
      - name: Check Build
        run: SKIP_WASM_BUILD=1 cargo check --release

      - name: Check Tests
        run: cargo test --release

      - name: Check Build for Benchmarking
        run: cargo check --features=runtime-benchmarks --release --manifest-path=node/Cargo.toml
